default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: maglev_core
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: maglev_core_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>